// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp1.EF;

#nullable disable

namespace WebApp1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260402115621_updateBooking")]
    partial class updateBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp1.Models.Client", b =>
                {
                    b.Property<int?>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ClientID"));

                    b.Property<string>("ClientName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientStatus")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApp1.Models.ClientBookingDetail", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<string>("Address")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckImagePath")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DownPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstInstallmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstallmentYears")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIdImagePath")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectCode")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationAmount")
                        .HasColumnType("int");

                    b.Property<bool?>("Reserved")
                        .HasColumnType("bit");

                    b.Property<string>("SecondaryPhone")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.ToTable("ClientBookingDetails");
                });

            modelBuilder.Entity("WebApp1.Models.Installment", b =>
                {
                    b.Property<int>("InstallmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstallmentID"));

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("CheckImage")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientBookingDetailBookingID")
                        .HasColumnType("int");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyAmount")
                        .HasColumnType("int");

                    b.Property<int?>("Months")
                        .HasColumnType("int");

                    b.Property<bool?>("Paid")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentType")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectCode")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.Property<string>("unitName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstallmentID");

                    b.HasIndex("ClientBookingDetailBookingID");

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("WebApp1.Models.Negotiation", b =>
                {
                    b.Property<int>("NegotiationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NegotiationID"));

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("NegotiationDate")
                        .HasColumnType("date");

                    b.Property<int?>("NegotiationPrice")
                        .HasColumnType("int");

                    b.Property<string>("NegotiationStatus")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginalPrice")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectCode")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requester")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.Property<bool?>("checkedByAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("serialCode")
                        .HasColumnType("int");

                    b.Property<string>("unitName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NegotiationID");

                    b.HasIndex("ClientID");

                    b.ToTable("Negotiations");
                });

            modelBuilder.Entity("WebApp1.Models.Project", b =>
                {
                    b.Property<int>("ProjectCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectCode"));

                    b.Property<string>("Location")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectImage")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectStatus")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalUnits")
                        .HasColumnType("int");

                    b.HasKey("ProjectCode");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WebApp1.Models.Rejected_negotiations_phase", b =>
                {
                    b.Property<int>("PhaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhaseID"));

                    b.Property<DateTime?>("CheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<bool?>("NegotiationCondition")
                        .HasColumnType("bit");

                    b.Property<int?>("ProjectCode")
                        .HasColumnType("int");

                    b.Property<string>("ReasonOfReject")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuggestedPrice")
                        .HasColumnType("int");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("PhaseID");

                    b.ToTable("Rejected_negotiations_phases");
                });

            modelBuilder.Entity("WebApp1.Models.Unit", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitID"));

                    b.Property<string>("Floor")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeterPrice")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectCode")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectCode1")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReservedStatus")
                        .HasColumnType("bit");

                    b.Property<float?>("TotalArea")
                        .HasColumnType("real");

                    b.Property<float?>("TotalPrice")
                        .HasColumnType("real");

                    b.Property<int?>("serial")
                        .HasColumnType("int");

                    b.Property<string>("unitImage")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unitName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitID");

                    b.HasIndex("ProjectCode1");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("WebApp1.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApp1.Models.Installment", b =>
                {
                    b.HasOne("WebApp1.Models.ClientBookingDetail", null)
                        .WithMany("installments")
                        .HasForeignKey("ClientBookingDetailBookingID");
                });

            modelBuilder.Entity("WebApp1.Models.Negotiation", b =>
                {
                    b.HasOne("WebApp1.Models.Client", null)
                        .WithMany("negotiations")
                        .HasForeignKey("ClientID");
                });

            modelBuilder.Entity("WebApp1.Models.Unit", b =>
                {
                    b.HasOne("WebApp1.Models.Project", null)
                        .WithMany("units")
                        .HasForeignKey("ProjectCode1");
                });

            modelBuilder.Entity("WebApp1.Models.Client", b =>
                {
                    b.Navigation("negotiations");
                });

            modelBuilder.Entity("WebApp1.Models.ClientBookingDetail", b =>
                {
                    b.Navigation("installments");
                });

            modelBuilder.Entity("WebApp1.Models.Project", b =>
                {
                    b.Navigation("units");
                });
#pragma warning restore 612, 618
        }
    }
}
